version: '3'

networks:
  bucket_cinema_ticket:
    driver: bridge

services:

  postgres_db:
    image: postgres:9.6
    container_name: postgres_db
    networks:
      - bucket_cinema_ticket
    env_file: .env.db_postgres
    ports:
      - '5432:5432'

  kong_api_gateway:
    image: kong/kong-gateway:2.8.0.0-alpine
    container_name: kong_api_gateway
    env_file: .env.kong
    restart: always
#    command: "kong migrations bootstrap"
#    volumes:
#      - ./devops/kong/config:/etc/kong
    networks:
      - bucket_cinema_ticket
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
#  nginx:
#    image: nginx:latest
#    container_name: nginx_web_server
#    ports: [ '8001:80' ]
#    volumes:
#      - ./devops/nginx/conf:/etc/nginx/conf.d
#      - /volumes/nginx/logs:/var/log/nginx
#    networks: [ 'bucket_cinema_ticket' ]
#
#  rabbitmq_notification_broker:
#    image: rabbitmq:3-management-alpine
#    container_name: rabbitmq_notification_broker
#    ports: [ "5672:5672", "15672:15672" ]
#    volumes:
#      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
#      # - ./volumes/rabbitmq/log/:/var/log/rabbitmq
#    networks: [ 'bucket_cinema_ticket' ]