version: '3'

networks:
  bucket_cinema_ticket:
    driver: bridge

services:

  postgres_db:
    image: postgres:9.6
    container_name: postgres_db
    networks:
      - bucket_cinema_ticket
    env_file: ./devops/environments/.env.db_postgres
    ports:
      - '5432:5432'

  kong_api_gateway:
    image: kong/kong-gateway:2.8.0.0-alpine
    container_name: kong_api_gateway
    env_file: ./devops/environments/.env.kong
    restart: always
    # command: "kong migrations bootstrap"
    #    volumes:
    #      - ./devops/kong/config:/etc/kong
    networks:
      - bucket_cinema_ticket
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004

  nginx:
    image: nginx:latest
    container_name: nginx_web_server
    ports: [ '8088:80', '9000:9000' ]
    volumes:
      - ./devops/nginx/conf:/etc/nginx/conf.d
      - ./volumes/nginx/logs:/var/log/nginx
    networks: [ 'bucket_cinema_ticket' ]

  rabbitmq_notification_broker:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_notification_broker
    ports: [ "5672:5672", "15672:15672" ]
    volumes:
      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
      # - ./volumes/rabbitmq/log/:/var/log/rabbitmq
    networks: [ 'bucket_cinema_ticket' ]

  mysql:
    image: mysql:8.5
    container_name: mysql_db06
    ports:
      - "3306:3306"
    env_file: ./devops/environments/.env.mysql
    networks: [ 'bucket_cinema_ticket' ]

  phpmyadmin:
    image: phpmyadmin:phpmyadmin:latest
    container_name: phpmyadmin
    ports: []
    networks: [ 'bucket_cinema_ticket' ]
    env_file: ./devops/environments/.env.phpmyadmin

  # application services as container
  admin_service:
    container_name: admin_service
    build:
      context: ./admin-service/
      dockerfile: ./admin-service/Dockerfile
    ports: ['9000:9000']
    networks: ['bucket_cinema_ticket']
    env_file:
      - ./devops/environments/.env.admin_service
    volumes:
    - ./admin-service:./var/www/html/

  admin_ui_service:
      container_name: admin_ui_service
#      ports:
      networks:
        - bucket_cinema_ticket
        -